version: "3.9"

## Notes
##  - restart-policy : https://docs.docker.com/config/containers/start-containers-automatically/

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - db
    logging:
      driver: none

networks:
  db: {}

volumes:
  postgres:
  pgadmin:
